name: new bean co
favicon: null
layout_spectrum: 0.001960993278771639
typography_spectrum: 0.8309119290206581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191717'
    - '#4b423d'
    - '#858d99'
    - '#cac9c9'
  brandStrength: 0.1875
  lightness: 0.40149011043831706
  saturation: 0.4340103443246335
  rhythmicContrast: 0.6987903018016368
purpose: []
